clone_depth: 200

environment:
  global:
    MINGW: C:\Qt\Tools\mingw530_32
  matrix:
    - QTDIR: C:\Qt\5.7\mingw53_32

configuration: Release

install:
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin

build_script:
  - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - if defined APPVEYOR_REPO_TAG_NAME set BUILD_INFO_VERSION=%VERSION%
  - if defined APPVEYOR_REPO_TAG_NAME echo Building VChar64 %VERSION%... (from %COMMITNOW%)
  - if not defined APPVEYOR_REPO_TAG_NAME set VERSION=%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%
  - if not defined APPVEYOR_REPO_TAG_NAME set BUILD_INFO_VERSION=%COMMITNOW%
  - if not defined APPVEYOR_REPO_TAG_NAME echo Building VChar64 daily %VERSION%... (from %COMMITNOW%)
  - qmake
  - mingw32-make

