language: cpp
sudo: required
dist: trusty
services:
  - docker

matrix:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
          env: QMAKESPEC=linux-clang
        - os: osx

env:
  - QT=57 BREW=ex PPA=beineri/opt-qt57-trusty

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:$PPA
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qy ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt5 --force ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qy qt5-default qttools5-dev-tools cppcheck; fi
  - qmake -version


script:
  - qmake
  - make

after_script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cppcheck --enable=all -q -Isrc/ `git ls-files src/\*.cpp` ; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf558929fabd79e35091
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

