language: cpp
sudo: required
dist: trusty
services:
  - docker

matrix:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
          env: QMAKESPEC=linux-clang
        - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt5 --force ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -qq qt5-default qttools5-dev-tools cppcheck; fi
  - qmake -version
    

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install cppcheck'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'


script:
  - qmake
  - make

after_script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cppcheck --enable=all -q -Isrc/ `git ls-files src/\*.cpp` ; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf558929fabd79e35091
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

