language: cpp
sudo: false

matrix:
    include:
        - compiler: gcc
        - compiler: clang
          env: QMAKESPEC=linux-clang
addons:
  apt:
    packages:
      - qt5-default
      - qttools5-dev-tools
      - cppcheck

before_install:
  - qmake -version
script:
  - qmake
  - make
after_script: cppcheck --enable=all -q -Isrc/ `git ls-files src/\*.cpp`
