clone_depth: 200

environment:
  global:
    MINGW: C:\Qt\Tools\mingw492_32
  matrix:
    - QTDIR: C:\Qt\5.5\mingw492_32
    - QTDIR: C:\Qt\5.5\msvc2013_64

configuration: Release

install:
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin

build_script:
  - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - if defined APPVEYOR_REPO_TAG_NAME set BUILD_INFO_VERSION=%VERSION%
  - if defined APPVEYOR_REPO_TAG_NAME echo Building Tiled %VERSION%... (from %COMMITNOW%)
  - if not defined APPVEYOR_REPO_TAG_NAME set VERSION=%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%
  - if not defined APPVEYOR_REPO_TAG_NAME set BUILD_INFO_VERSION=%COMMITNOW%
  - if not defined APPVEYOR_REPO_TAG_NAME echo Building Tiled daily %VERSION%... (from %COMMITNOW%)
  - qbs setup-toolchains --detect
  - qbs config profiles.i686-w64-mingw32.cpp.archiverPath ar.exe
  - qbs config profiles.i686-w64-mingw32.cpp.nmPath nm.exe
  - qbs config profiles.i686-w64-mingw32.cpp.objcopyPath objcopy.exe
  - qbs config profiles.i686-w64-mingw32.cpp.stripPath strip.exe
  - qbs setup-qt %QTDIR%\bin\qmake.exe qt
  - qbs config defaultProfile qt
  - qbs install --all-products --install-root install-root release

