version: 1.0.{build}

image: Visual Studio 2015

environment:
  matrix:
    - QTDIR: C:\Qt\5.9.5\mingw53_32
      MINGW: C:\Qt\Tools\mingw530_32

configuration: Release

install:
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin

build_script:
  - qmake
  - mingw32-make

test: off
